# Use a imagem base do PHP com Apache
FROM php:8.1-apache

# Instale as dependências necessárias
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl

# Instale o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Verifique se o Composer foi instalado corretamente
RUN composer --version

# Defina o diretório de trabalho
WORKDIR /var/www/html

# Copie os arquivos do projeto para o contêiner
COPY . .

# Instale as dependências do Laravel
RUN composer install

# Adicione a dependência smalot/text2vec
RUN composer require smalot/text2vec

# Instale as dependências do Node.js e compile os assets do Vue.js
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    && npm install \
    && npm run dev

# Defina as permissões corretas
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Exponha a porta 80
EXPOSE 80

# Inicie o servidor Apache
CMD ["apache2-foreground"]