services:
  backend:
    build: 
      context: .
      dockerfile: DockerFile
    container_name: laravel_backend
    working_dir: /var/www/html
    volumes:
      - ./backendPHP:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - 8000:80

  frontend:
    build: 
      context: ./
      dockerfile: web.dockerfile
    restart: unless-stopped
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./frontendVue:/app
    links:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    ports:
      - 80:8080
    command: sh -c "npm install --legacy-peer-deps && npm run dev"

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  app-network:
    driver: bridge
